spring.application.name=ds

spring.out.put.ansi.enabled=ALWAYS

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://10.200.4.221:3306/david_chaves_ds?createDatabaseIfNotExist=true
spring.datasource.username=david_chaves
spring.datasource.password=manequinho23
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
